name: "Deploy the code on push"

on:
  push:
    branches:
      - main

jobs:
  backendDeploy:
    name: "deploy the backend code"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the backend code"
        uses: actions/checkout@v2

      - name: "setup node.js"
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: "install the npm dep"
        run: npm install

      - name: "build the backend code"
        run: npm run build

      - name: login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN}}

      - name: "Build and Push Docker image to DockerHub"
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          push: true
          tags: akshaydhayal/medium_blog_backend:latest
